name: CI Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5 
        with:
          python-version: 3.11.7

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run pytest
        run: poetry run pytest tests -v